#Baseimage /it has to be in any dockerfile
FROM openjdk:17-jdk

COPY ./target/Spring-24-Docker-0.0.1-SNAPSHOT.jar /usr/app/

WORKDIR /usr/app

ENTRYPOINT ["java", "-jar", "Spring-24-Docker-0.0.1-SNAPSHOT.jar"]